# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.auto_areas: debug

# https://www.home-assistant.io/integrations/demo/

demo:

sensor:
  - platform: random
    minimum: 0
    maximum: 200

  - platform: template
    sensors:
      illuminance_a:
        unique_id: sensor.illuminance_a
        friendly_name: Illuminance a
        icon_template: mdi:brightness-auto
        unit_of_measurement: lx
        value_template: "{{ states('sensor.random_sensor') | float * 1.2 }}"
        device_class: illuminance
      illuminance_b:
        unique_id: sensor.illuminance_b
        friendly_name: Illuminance b
        icon_template: mdi:brightness-auto
        unit_of_measurement: lx
        value_template: "{{ states('sensor.random_sensor') | float * 1.3 }}"
        device_class: illuminance
      illuminance_c:
        unique_id: sensor.illuminance_c
        friendly_name: Illuminance c
        icon_template: mdi:brightness-auto
        unit_of_measurement: lx
        value_template: "{{ states('sensor.random_sensor') | float * 1.35 }}"
        device_class: illuminance
      illuminance_d:
        unique_id: sensor.illuminance_d
        friendly_name: Illuminance d
        icon_template: mdi:brightness-auto
        unit_of_measurement: lx
        value_template: "{{ states('sensor.random_sensor') | float * 0.9 }}"
