name: "Validate"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4.1.7"

        - name: "Run hassfest validation"
          uses: "home-assistant/actions/hassfest@master"

  hacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4.1.7"

        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "integration"

  test:
    name: "Unit tests"
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4.1.7"

        - name: "Set up Python"
          uses: actions/setup-python@v5.6.0
          with:
            python-version: "3.12"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements-test.txt

        - name: Run tests with coverage
          run: pytest --cov=custom_components.auto_areas --cov-report=xml --cov-report=term

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.xml
            flags: unittests
            name: codecov-umbrella
            fail_ci_if_error: false
